### ISSUE TITLE
Selection not highlighted

### ISSUE THREAD

**Issue by sirajc** [fergaldoyle/brackets-visual-studio-dark#3]
Since version 1.5 of brackets, selection is not highlighted

**Comment by derrickb** [comment]
I'm also having this problem.  Did a complete fresh install of Brackets + extensions but this theme still isn't showing highlighted text.  Have to switch to another theme for now, which is a shame.  Hopefully it can get resolved soon!

**Comment by fergaldoyle** [comment]
Fixed with 6a8855c37379315b1f5d0fe7978483258487a90f

Updated published.
